<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'ArithmeticError' => $vendorDir . '/symfony/polyfill/src/Php70/Resources/stubs/ArithmeticError.php',
    'AssertionError' => $vendorDir . '/symfony/polyfill/src/Php70/Resources/stubs/AssertionError.php',
    'Byteart\\Mailer\\Base' => $baseDir . '/core/Base.php',
    'Byteart\\Mailer\\Console' => $baseDir . '/core/Console.php',
    'Byteart\\Mailer\\Db' => $baseDir . '/core/Db.php',
    'Byteart\\Mailer\\Email' => $baseDir . '/core/Email.php',
    'Byteart\\Mailer\\Lists' => $baseDir . '/core/Lists.php',
    'Byteart\\Mailer\\SmartMailer' => $baseDir . '/core/SmartMailer.php',
    'Byteart\\Mailer\\Smtp' => $baseDir . '/core/Smtp.php',
    'CallbackFilterIterator' => $vendorDir . '/symfony/polyfill/src/Php54/Resources/stubs/CallbackFilterIterator.php',
    'Collator' => $vendorDir . '/symfony/intl/Resources/stubs/Collator.php',
    'DivisionByZeroError' => $vendorDir . '/symfony/polyfill/src/Php70/Resources/stubs/DivisionByZeroError.php',
    'EasyPeasyICS' => $vendorDir . '/phpmailer/phpmailer/extras/EasyPeasyICS.php',
    'Error' => $vendorDir . '/symfony/polyfill/src/Php70/Resources/stubs/Error.php',
    'IntlDateFormatter' => $vendorDir . '/symfony/intl/Resources/stubs/IntlDateFormatter.php',
    'Locale' => $vendorDir . '/symfony/intl/Resources/stubs/Locale.php',
    'Normalizer' => $vendorDir . '/symfony/polyfill/src/Intl/Normalizer/Resources/stubs/Normalizer.php',
    'NumberFormatter' => $vendorDir . '/symfony/intl/Resources/stubs/NumberFormatter.php',
    'PHPMailer' => $vendorDir . '/phpmailer/phpmailer/class.phpmailer.php',
    'PHPMailerOAuth' => $vendorDir . '/phpmailer/phpmailer/class.phpmaileroauth.php',
    'PHPMailerOAuthGoogle' => $vendorDir . '/phpmailer/phpmailer/class.phpmaileroauthgoogle.php',
    'POP3' => $vendorDir . '/phpmailer/phpmailer/class.pop3.php',
    'ParseError' => $vendorDir . '/symfony/polyfill/src/Php70/Resources/stubs/ParseError.php',
    'RecursiveCallbackFilterIterator' => $vendorDir . '/symfony/polyfill/src/Php54/Resources/stubs/RecursiveCallbackFilterIterator.php',
    'SMTP' => $vendorDir . '/phpmailer/phpmailer/class.smtp.php',
    'SessionHandlerInterface' => $vendorDir . '/symfony/polyfill/src/Php54/Resources/stubs/SessionHandlerInterface.php',
    'SessionUpdateTimestampHandlerInterface' => $vendorDir . '/symfony/polyfill/src/Php70/Resources/stubs/SessionUpdateTimestampHandlerInterface.php',
    'TypeError' => $vendorDir . '/symfony/polyfill/src/Php70/Resources/stubs/TypeError.php',
    'ntlm_sasl_client_class' => $vendorDir . '/phpmailer/phpmailer/extras/ntlm_sasl_client.php',
    'phpmailerException' => $vendorDir . '/phpmailer/phpmailer/class.phpmailer.php',
);
